spin_manifest_version = 2

[application]
name = "outbound-http"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple Spin application written in (Tiny)Go that performs outbound HTTP requests."
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "main.wasm"
allowed_outbound_hosts = ["https://random-data-api.fermyon.app:443"]
[component.hello.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm main.go"
