spin_manifest_version = 2

[application]
name = "hello-world"
version = "0.1.0"
authors = ["Caleb Schoepp <caleb.schoepp@fermyon.com>"]
description = "A simple hello world Spin app"

[[trigger.http]]
route = "/..."
component = "hello-world"

[component.hello-world]
source = "main.wasm"
allowed_outbound_hosts = []
[component.hello-world.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
