apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: annotations-spinapp
spec:
  image: "ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0"
  replicas: 1
  executor: containerd-shim-spin
  serviceAnnotations:
    key: value
  deploymentAnnotations:
    key: value
    multiple-keys: are-supported
  podAnnotations:
    key: value
