apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: healthchecks-spinapp
spec:
  image: "ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0"
  replicas: 1
  executor: containerd-shim-spin
  checks:
    liveness:
      httpGet:
        path: "/hello"
    readiness:
      httpGet:
        path: "/go-hello"
