apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: redis-spinapp
spec:
  image: "ghcr.io/spinframework/spin-operator/redis-sample:20250625-200716-g19414c1"
  replicas: 1
  executor: containerd-shim-spin
# Steps to run this found at https://github.com/spinframework/spin-operator/pull/131