apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: runtime-config
spec:
  image: "ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0"
  replicas: 1
  executor: containerd-shim-spin
  runtimeConfig:
    sqliteDatabases:
      - name: "default"
        type: "libsql"
        options:
          - name: "url"
            value: "https://sensational-penguin-ahacker.libsql.example.com"
          - name: "token"
            valueFrom:
              secretKeyRef:
                name: "my-super-secret"
                key: "turso-token"

    llmCompute:
      type: "remote_http"
      options:
        - name: "url"
          value: "https://llm-app.fermyon.app"
        - name: "auth_token"
          valueFrom:
            secretKeyRef:
              name: "my-super-secret"
              key: "llm-token"

    keyValueStores:
      - name: "default"
        type: "redis"
        options:
          - name: "url"
            valueFrom:
              secretKeyRef:
                name: "my-super-secret"
                key: "redis-full-url"

