apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: hello-salutation-spinapp
spec:
  image: "ghcr.io/spinframework/spin-operator/salutations:20250625-200719-g19414c1"
  replicas: 1
  executor: containerd-shim-spin
  # Configure the application to only contain the "hello" component
  # Who doesn't hate goodbyes?
  components: ["hello"]
