apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: spintainer-spinapp
spec:
  image: "ghcr.io/spinframework/spin-operator/hello-world:20250625-200716-g19414c1"
  replicas: 1
  executor: spintainer
