spin_manifest_version = 2

[application]
name = "cpu-load-gen"
version = "0.1.0"
authors = ["Caleb Schoepp <caleb.schoepp@fermyon.com>"]
description = "A simple Spin app that will generate lots of load on the CPU by computing large fibonacci sequences"

[[trigger.http]]
route = "/..."
component = "cpu-load-gen"

[component.cpu-load-gen]
source = "main.wasm"
allowed_outbound_hosts = []
[component.cpu-load-gen.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
